// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN_i98GQIfQmoQyfCt2YwKbXMKy2RcLjE',
    appId: '1:656484553468:android:7c20aeebbd813bc61b7d79',
    messagingSenderId: '656484553468',
    projectId: 'chatnest-246ac',
    storageBucket: 'chatnest-246ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN2NRjberdOxdOXDdi0FGX_UvyL0TB5U8',
    appId: '1:656484553468:ios:8f104f36b1b661971b7d79',
    messagingSenderId: '656484553468',
    projectId: 'chatnest-246ac',
    storageBucket: 'chatnest-246ac.appspot.com',
    iosBundleId: 'com.example.gomeet',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhUyVh1uh-0tUx8coOG2_9gUpAGGP8pFc',
    appId: '1:656484553468:web:3aa86d45507b95fe1b7d79',
    messagingSenderId: '656484553468',
    projectId: 'chatnest-246ac',
    authDomain: 'chatnest-246ac.firebaseapp.com',
    storageBucket: 'chatnest-246ac.appspot.com',
    measurementId: 'G-HEL0RQ842X',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN2NRjberdOxdOXDdi0FGX_UvyL0TB5U8',
    appId: '1:656484553468:ios:8f104f36b1b661971b7d79',
    messagingSenderId: '656484553468',
    projectId: 'chatnest-246ac',
    storageBucket: 'chatnest-246ac.appspot.com',
    iosBundleId: 'com.example.gomeet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhUyVh1uh-0tUx8coOG2_9gUpAGGP8pFc',
    appId: '1:656484553468:web:241a49598859299e1b7d79',
    messagingSenderId: '656484553468',
    projectId: 'chatnest-246ac',
    authDomain: 'chatnest-246ac.firebaseapp.com',
    storageBucket: 'chatnest-246ac.appspot.com',
    measurementId: 'G-1SKN679LYY',
  );

}